General Statistical Methods
=============================

There are several important concepts that we will adhere to in our group.  These involve design considerations, execution considerations and analysis concerns.

```{r intial-setup, echo=FALSE, message=FALSE}
require(knitcitations)
bib <- read.bibtex("references.bib")

```

Experimental Design
--------------------

Where possible, prior to performing an experiment or study perform a power analysis.  This is mainly to determine the appropriate sample sizes.  To do this, you need to know a few of things:

* Either the sample size or the difference.  The difference is provided in standard deviations.  This means that you need to know the standard deviation of your measurement in question.  It is a good idea to keep a log of these for your data, so that you can approximate what this is.  If you hope to detect a correlation you will need to know the expected correlation coefficient.
* The desired false positive rate (normally 0.05).  This is the rate at which you find a difference where there is none.  This is also known as the type I error rate.
* The desired power (normally 0.8).  This indicates that 80% of the time you will detect the effect if there is one.  This is also known as 1 minus the false negative rate or 1 minus the Type II error rate.

We use the R package **pwr** to do a power analysis `r citet(bib['pwr'])`.  Here is an example:

### Pairwise Comparasons

```{r pwr-t-test, message=FALSE}
require(pwr)
false.negative.rate <- 0.05
statistical.power <- 0.8
sd <- 3.5 #this is calculated from known measurements
difference <- 3  #you hope to detect a difference 
pwr.t.test(d = difference, sig.level = false.negative.rate, power=statistical.power)
```
This tells us that in order to see a difference of at least `r difference`, with at standard devation of `r sd` we need at least **`r as.integer(pwr.t.test(d = difference, sig.level = false.negative.rate, power=statistical.power)$n)`** observations in each group.

### Correlations

The following is an example for detecting a correlation.  

```{r pwr-r-test, message=FALSE}
require(pwr)
false.negative.rate <- 0.05
statistical.power <- 0.8
correlation.coefficient <- 0.6 #note that this is the r, to get the R2 value you will have to square this result.
pwr.r.test(r = correlation.coefficient, sig.level = false.negative.rate, power=statistical.power)
```

This tells us that in order to detect a correlation coefficient of at least `r correlation.coefficient` (or an R^2 of `r correlation.coefficient^2`) you need more than **`r as.integer(pwr.r.test(r = correlation.coefficient, sig.level = false.negative.rate, power=statistical.power)$n)`** observations.

References
-----------

```{r bibliography, results='asis', echo=FALSE, message=FALSE}
require(bibtex)
write.bib(c(names(sessionInfo()$otherPkgs),'base','stats','utils'), file='references.bib')
bibliography("html") 
```